=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter06_schemas/al7.xsd
<?xml version="1.0"?>
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.wrox.com/catalog"
  xmlns:target="http://www.wrox.com/catalog"
  elementFormDefault="qualified">

 <element name="catalog">
   <complexType>
     <choice maxOccurs="unbounded">
       <element name="CD">
         <complexType>
           <group ref="target:AlbumGroup"/>
         </complexType>
       </element>
       <element name="cassette">
         <complexType>
           <group ref="target:AlbumGroup"/>
         </complexType>
       </element>
       <element name="record">
         <complexType>
           <group ref="target:AlbumGroup"/>
         </complexType>
       </element>
       <element name="MP3">
         <complexType>
           <group ref="target:AlbumGroup"/>
         </complexType>
       </element>
     </choice>
   </complexType>
 </element>

 <group name="AlbumGroup">
   <sequence>
     <element name="artist" type="string"/>
     <element name="title" type="string"/>
     <element name="genre" type="string"/>
     <element name="date-released" type="string"/>
     <element name="song" type="target:SongType" maxOccurs="unbounded"/>
   </sequence>
 </group>

 <complexType name="SongType">
   <sequence>
     <element name="title" type="string"/>
     <element name="length" type="target:LengthType"/>
     <element name="parody" type="target:ParodyType"/>
     <element name="lyrics" type="string"/>
   </sequence>
 </complexType>

 <complexType name="LengthType">
   <sequence>
     <element name="minutes" type="string"/>
     <element name="seconds" type="string"/>
   </sequence>
 </complexType>

 <complexType name="ParodyType">
   <sequence minOccurs="0">
     <element name="title" type="string"/>
     <element name="artist" type="string"/>
   </sequence>
 </complexType>

</schema>

=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter06_schemas/al7.xml
<?xml version="1.0"?>
<catalog
  xmlns="http://www.wrox.com/catalog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.wrox.com/catalog al7.xsd">
   <CD>
      <artist>"Weird Al" Yankovic</artist>
      <title>Dare to be Stupid</title>
      <genre>parody</genre>
      <date-released>1990</date-released>
      <song>
         <title>Like A Surgeon</title>
         <length>
            <minutes>3</minutes>
            <seconds>33</seconds>
         </length>
         <parody>
            <title>Like A Virgin</title>
            <artist>Madonna</artist>
         </parody>
         <lyrics></lyrics>
      </song>
      <song>
         <title>Dare to be Stupid</title>
         <length>
            <minutes>3</minutes>
            <seconds>25</seconds>
         </length>
         <parody></parody>
         <lyrics></lyrics>
      </song>
   </CD>
</catalog>
