=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter07_adv_schemas/name9.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wrox.com/name" xmlns:target="http://www.wrox.com/name" elementFormDefault="qualified">
  <complexType name="NameType">
    <sequence>
      <element name="first" type="string"/>
      <element name="middle" type="string"/>
      <element name="last" type="string"/>
    </sequence>
    <attribute name="title" type="string"/>
  </complexType>
  <complexType name="ExtendedNameType">
    <complexContent>
      <extension base="target:NameType">
        <sequence>
          <element name="age" type="positiveInteger"/>
          <element name="birthdate" type="dateTime"/>
        </sequence>
        <attribute name="gender" type="string"/>
      </extension>
    </complexContent>
  </complexType>
  <element name="names">
    <complexType>
      <sequence>
        <element name="name" type="target:NameType" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
</schema>

=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter07_adv_schemas/name9.xml
<?xml version="1.0"?>
<names
  xmlns="http://www.wrox.com/name"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.wrox.com/name name9.xsd">
  <name title="Mr.">
    <first>John</first>
    <middle>Fitzgerald</middle>
    <last>Doe</last>
  </name>
  <name title="Mr." gender="male" xsi:type="ExtendedNameType">
    <first>Weird</first>
    <middle>Al</middle>
    <last>Yankovic</last>
    <age>41</age>
    <birthdate>1959-10-23T13:56:00.000-08:00</birthdate>
  </name>
  <name title="Mrs." xsi:type="NameType">
    <first>Jane</first>
    <middle></middle>
    <last>Doe</last>
  </name>
</names>
