=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter07_adv_schemas/name10.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wrox.com/name" xmlns:target="http://www.wrox.com/name" elementFormDefault="qualified">
  <!-- Global elements used for element substitution -->
  <element name="name" type="target:NameType"/>
  <element name="person" type="target:NameType" substitutionGroup="target:name"/>
  <element name="ageName" type="target:ExtendedNameType" substitutionGroup="target:name"/>
  <!-- Our NameType from our earlier examples -->
  <complexType name="NameType">
    <sequence>
      <element name="first" type="string"/>
      <element name="middle" type="string"/>
      <element name="last" type="string"/>
    </sequence>
    <attribute name="title" type="string"/>
  </complexType>
  <!-- The new ExtendedNameType that inherits from NameType -->
  <complexType name="ExtendedNameType">
    <complexContent>
      <extension base="target:NameType">
        <sequence>
          <element name="age" type="positiveInteger"/>
          <element name="birthdate" type="dateTime"/>
        </sequence>
        <attribute name="gender" type="string"/>
      </extension>
    </complexContent>
  </complexType>
  <!-- We will use the names element as the root in our instance document -->
  <element name="names">
    <complexType>
      <sequence>
        <!-- We declare our name element using a reference to a global declaration -->
        <element ref="target:name" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
</schema>

=== vivlavie/PyXML/BeginningXML/Code Download/5598_chapter07_adv_schemas/name10.xml
<?xml version="1.0"?>
<names
  xmlns="http://www.wrox.com/name"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.wrox.com/name name10.xsd">
  <name title="Mr.">
    <first>John</first>
    <middle>Fitzgerald</middle>
    <last>Doe</last>
  </name>
  <ageName title="Mr." gender="male">
    <first>Weird</first>
    <middle>Al</middle>
    <last>Yankovic</last>
    <age>41</age>
    <birthdate>1959-10-23T13:56:00.000-08:00</birthdate>
  </ageName>
  <person title="Mrs.">
    <first>Jane</first>
    <middle></middle>
    <last>Doe</last>
  </person>
</names>
